#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChatApp")]
	public partial class ChatAppLQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbAttachmment(tbAttachmment instance);
    partial void UpdatetbAttachmment(tbAttachmment instance);
    partial void DeletetbAttachmment(tbAttachmment instance);
    partial void InserttbUser(tbUser instance);
    partial void UpdatetbUser(tbUser instance);
    partial void DeletetbUser(tbUser instance);
    partial void InserttbConversation(tbConversation instance);
    partial void UpdatetbConversation(tbConversation instance);
    partial void DeletetbConversation(tbConversation instance);
    partial void InserttbConversation_User(tbConversation_User instance);
    partial void UpdatetbConversation_User(tbConversation_User instance);
    partial void DeletetbConversation_User(tbConversation_User instance);
    partial void InserttbFriend(tbFriend instance);
    partial void UpdatetbFriend(tbFriend instance);
    partial void DeletetbFriend(tbFriend instance);
    partial void InserttbMessage(tbMessage instance);
    partial void UpdatetbMessage(tbMessage instance);
    partial void DeletetbMessage(tbMessage instance);
    partial void InserttbUser_Friend(tbUser_Friend instance);
    partial void UpdatetbUser_Friend(tbUser_Friend instance);
    partial void DeletetbUser_Friend(tbUser_Friend instance);
    #endregion
		
		public ChatAppLQDataContext() : 
				base(global::Model.Properties.Settings.Default.ChatAppConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChatAppLQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatAppLQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatAppLQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatAppLQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbAttachmment> tbAttachmments
		{
			get
			{
				return this.GetTable<tbAttachmment>();
			}
		}
		
		public System.Data.Linq.Table<tbUser> tbUsers
		{
			get
			{
				return this.GetTable<tbUser>();
			}
		}
		
		public System.Data.Linq.Table<tbConversation> tbConversations
		{
			get
			{
				return this.GetTable<tbConversation>();
			}
		}
		
		public System.Data.Linq.Table<tbConversation_User> tbConversation_Users
		{
			get
			{
				return this.GetTable<tbConversation_User>();
			}
		}
		
		public System.Data.Linq.Table<tbFriend> tbFriends
		{
			get
			{
				return this.GetTable<tbFriend>();
			}
		}
		
		public System.Data.Linq.Table<tbMessage> tbMessages
		{
			get
			{
				return this.GetTable<tbMessage>();
			}
		}
		
		public System.Data.Linq.Table<tbUser_Friend> tbUser_Friends
		{
			get
			{
				return this.GetTable<tbUser_Friend>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddFriend")]
		public int AddFriend([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridchudong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridbidong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useridchudong, useridbidong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UnFriend")]
		public int UnFriend([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridchudong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridbidong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useridchudong, useridbidong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddUserToConversation")]
		public int AddUserToConversation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, conversationid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BlockFriend")]
		public int BlockFriend([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridchudong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridbidong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useridchudong, useridbidong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NewConversation")]
		public int NewConversation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isgroup)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversationid, name, isgroup);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UnBlockFriend")]
		public int UnBlockFriend([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridchudong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string useridbidong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useridchudong, useridbidong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcBlockFriendList", IsComposable=true)]
		public IQueryable<funcBlockFriendListResult> funcBlockFriendList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcBlockFriendListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcSeachFriendList", IsComposable=true)]
		public IQueryable<funcSeachFriendListResult> funcSeachFriendList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcSeachFriendListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcCheckOnlineCS", IsComposable=true)]
		public System.Nullable<bool> funcCheckOnlineCS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversationid).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcConversationSMS", IsComposable=true)]
		public IQueryable<funcConversationSMSResult> funcConversationSMS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcConversationSMSResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcGetListFriend", IsComposable=true)]
		public IQueryable<funcGetListFriendResult> funcGetListFriend([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcGetListFriendResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcLastSMSConversation", IsComposable=true)]
		public IQueryable<funcLastSMSConversationResult> funcLastSMSConversation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid)
		{
			return this.CreateMethodCallQuery<funcLastSMSConversationResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversationid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcMyNewID", IsComposable=true)]
		public string funcMyNewID()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcMyNewIDConversation", IsComposable=true)]
		public string funcMyNewIDConversation()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcMyNewIDFriend", IsComposable=true)]
		public string funcMyNewIDFriend()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcMyNewIDMessage", IsComposable=true)]
		public string funcMyNewIDMessage()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcMyNewIDUser", IsComposable=true)]
		public string funcMyNewIDUser()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcOnlineStatusConversation", IsComposable=true)]
		public System.Nullable<bool> funcOnlineStatusConversation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversationid).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateProfile")]
		public int updateProfile([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string pathImage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string nameshow, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> birth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, pathImage, nameshow, email, birth, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcFindConversationName", IsComposable=true)]
		public IQueryable<funcFindConversationNameResult> funcFindConversationName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid)
		{
			return this.CreateMethodCallQuery<funcFindConversationNameResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, conversationid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcOfflineList", IsComposable=true)]
		public IQueryable<funcOfflineListResult> funcOfflineList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcOfflineListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcOnlineList", IsComposable=true)]
		public IQueryable<funcOnlineListResult> funcOnlineList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcOnlineListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcGetListMessage", IsComposable=true)]
		public IQueryable<funcGetListMessageResult> funcGetListMessage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string conversationid)
		{
			return this.CreateMethodCallQuery<funcGetListMessageResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversationid);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.funcGetAllConversation", IsComposable=true)]
		public IQueryable<funcGetAllConversationResult> funcGetAllConversation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string userid)
		{
			return this.CreateMethodCallQuery<funcGetAllConversationResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbAttachmment")]
	public partial class tbAttachmment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.Data.Linq.Binary _data;
		
		private System.Data.Linq.Binary _filetype;
		
		private string _filedot;
		
		private string _messageid;
		
		private EntityRef<tbMessage> _tbMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OndataChanging(System.Data.Linq.Binary value);
    partial void OndataChanged();
    partial void OnfiletypeChanging(System.Data.Linq.Binary value);
    partial void OnfiletypeChanged();
    partial void OnfiledotChanging(string value);
    partial void OnfiledotChanged();
    partial void OnmessageidChanging(string value);
    partial void OnmessageidChanged();
    #endregion
		
		public tbAttachmment()
		{
			this._tbMessage = default(EntityRef<tbMessage>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filetype", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary filetype
		{
			get
			{
				return this._filetype;
			}
			set
			{
				if ((this._filetype != value))
				{
					this.OnfiletypeChanging(value);
					this.SendPropertyChanging();
					this._filetype = value;
					this.SendPropertyChanged("filetype");
					this.OnfiletypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filedot", DbType="NChar(10)")]
		public string filedot
		{
			get
			{
				return this._filedot;
			}
			set
			{
				if ((this._filedot != value))
				{
					this.OnfiledotChanging(value);
					this.SendPropertyChanging();
					this._filedot = value;
					this.SendPropertyChanged("filedot");
					this.OnfiledotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_messageid", DbType="NChar(10)")]
		public string messageid
		{
			get
			{
				return this._messageid;
			}
			set
			{
				if ((this._messageid != value))
				{
					if (this._tbMessage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmessageidChanging(value);
					this.SendPropertyChanging();
					this._messageid = value;
					this.SendPropertyChanged("messageid");
					this.OnmessageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbMessage_tbAttachmment", Storage="_tbMessage", ThisKey="messageid", OtherKey="id", IsForeignKey=true)]
		public tbMessage tbMessage
		{
			get
			{
				return this._tbMessage.Entity;
			}
			set
			{
				tbMessage previousValue = this._tbMessage.Entity;
				if (((previousValue != value) 
							|| (this._tbMessage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbMessage.Entity = null;
						previousValue.tbAttachmments.Remove(this);
					}
					this._tbMessage.Entity = value;
					if ((value != null))
					{
						value.tbAttachmments.Add(this);
						this._messageid = value.id;
					}
					else
					{
						this._messageid = default(string);
					}
					this.SendPropertyChanged("tbMessage");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbUser")]
	public partial class tbUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _account;
		
		private string _password;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _sex;
		
		private string _nameshow;
		
		private System.Nullable<bool> _active;
		
		private string _role;
		
		private string _connectionid;
		
		private System.Nullable<bool> _onlinestatus;
		
		private string _pathimage;
		
		private EntitySet<tbConversation_User> _tbConversation_Users;
		
		private EntitySet<tbMessage> _tbMessages;
		
		private EntitySet<tbUser_Friend> _tbUser_Friends;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnaccountChanging(string value);
    partial void OnaccountChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnbirthChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OnnameshowChanging(string value);
    partial void OnnameshowChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnconnectionidChanging(string value);
    partial void OnconnectionidChanged();
    partial void OnonlinestatusChanging(System.Nullable<bool> value);
    partial void OnonlinestatusChanged();
    partial void OnpathimageChanging(string value);
    partial void OnpathimageChanged();
    #endregion
		
		public tbUser()
		{
			this._tbConversation_Users = new EntitySet<tbConversation_User>(new Action<tbConversation_User>(this.attach_tbConversation_Users), new Action<tbConversation_User>(this.detach_tbConversation_Users));
			this._tbMessages = new EntitySet<tbMessage>(new Action<tbMessage>(this.attach_tbMessages), new Action<tbMessage>(this.detach_tbMessages));
			this._tbUser_Friends = new EntitySet<tbUser_Friend>(new Action<tbUser_Friend>(this.attach_tbUser_Friends), new Action<tbUser_Friend>(this.detach_tbUser_Friends));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account", DbType="NChar(20)")]
		public string account
		{
			get
			{
				return this._account;
			}
			set
			{
				if ((this._account != value))
				{
					this.OnaccountChanging(value);
					this.SendPropertyChanging();
					this._account = value;
					this.SendPropertyChanged("account");
					this.OnaccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this.OnbirthChanging(value);
					this.SendPropertyChanging();
					this._birth = value;
					this.SendPropertyChanged("birth");
					this.OnbirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this.OnnameshowChanging(value);
					this.SendPropertyChanging();
					this._nameshow = value;
					this.SendPropertyChanged("nameshow");
					this.OnnameshowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NChar(10)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectionid", DbType="NChar(50)")]
		public string connectionid
		{
			get
			{
				return this._connectionid;
			}
			set
			{
				if ((this._connectionid != value))
				{
					this.OnconnectionidChanging(value);
					this.SendPropertyChanging();
					this._connectionid = value;
					this.SendPropertyChanged("connectionid");
					this.OnconnectionidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onlinestatus", DbType="Bit")]
		public System.Nullable<bool> onlinestatus
		{
			get
			{
				return this._onlinestatus;
			}
			set
			{
				if ((this._onlinestatus != value))
				{
					this.OnonlinestatusChanging(value);
					this.SendPropertyChanging();
					this._onlinestatus = value;
					this.SendPropertyChanged("onlinestatus");
					this.OnonlinestatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this.OnpathimageChanging(value);
					this.SendPropertyChanging();
					this._pathimage = value;
					this.SendPropertyChanged("pathimage");
					this.OnpathimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbConversation_User", Storage="_tbConversation_Users", ThisKey="id", OtherKey="userid")]
		public EntitySet<tbConversation_User> tbConversation_Users
		{
			get
			{
				return this._tbConversation_Users;
			}
			set
			{
				this._tbConversation_Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbMessage", Storage="_tbMessages", ThisKey="id", OtherKey="userid")]
		public EntitySet<tbMessage> tbMessages
		{
			get
			{
				return this._tbMessages;
			}
			set
			{
				this._tbMessages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbUser_Friend", Storage="_tbUser_Friends", ThisKey="id", OtherKey="user_id")]
		public EntitySet<tbUser_Friend> tbUser_Friends
		{
			get
			{
				return this._tbUser_Friends;
			}
			set
			{
				this._tbUser_Friends.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbConversation_Users(tbConversation_User entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = this;
		}
		
		private void detach_tbConversation_Users(tbConversation_User entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = null;
		}
		
		private void attach_tbMessages(tbMessage entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = this;
		}
		
		private void detach_tbMessages(tbMessage entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = null;
		}
		
		private void attach_tbUser_Friends(tbUser_Friend entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = this;
		}
		
		private void detach_tbUser_Friends(tbUser_Friend entity)
		{
			this.SendPropertyChanging();
			entity.tbUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbConversation")]
	public partial class tbConversation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _creationtime;
		
		private System.Nullable<System.DateTime> _lasttimemodified;
		
		private System.Nullable<bool> _isGroup;
		
		private EntitySet<tbConversation_User> _tbConversation_Users;
		
		private EntitySet<tbMessage> _tbMessages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncreationtimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreationtimeChanged();
    partial void OnlasttimemodifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnlasttimemodifiedChanged();
    partial void OnisGroupChanging(System.Nullable<bool> value);
    partial void OnisGroupChanged();
    #endregion
		
		public tbConversation()
		{
			this._tbConversation_Users = new EntitySet<tbConversation_User>(new Action<tbConversation_User>(this.attach_tbConversation_Users), new Action<tbConversation_User>(this.detach_tbConversation_Users));
			this._tbMessages = new EntitySet<tbMessage>(new Action<tbMessage>(this.attach_tbMessages), new Action<tbMessage>(this.detach_tbMessages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creationtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> creationtime
		{
			get
			{
				return this._creationtime;
			}
			set
			{
				if ((this._creationtime != value))
				{
					this.OncreationtimeChanging(value);
					this.SendPropertyChanging();
					this._creationtime = value;
					this.SendPropertyChanged("creationtime");
					this.OncreationtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lasttimemodified", DbType="DateTime")]
		public System.Nullable<System.DateTime> lasttimemodified
		{
			get
			{
				return this._lasttimemodified;
			}
			set
			{
				if ((this._lasttimemodified != value))
				{
					this.OnlasttimemodifiedChanging(value);
					this.SendPropertyChanging();
					this._lasttimemodified = value;
					this.SendPropertyChanged("lasttimemodified");
					this.OnlasttimemodifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isGroup", DbType="Bit")]
		public System.Nullable<bool> isGroup
		{
			get
			{
				return this._isGroup;
			}
			set
			{
				if ((this._isGroup != value))
				{
					this.OnisGroupChanging(value);
					this.SendPropertyChanging();
					this._isGroup = value;
					this.SendPropertyChanged("isGroup");
					this.OnisGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbConversation_tbConversation_User", Storage="_tbConversation_Users", ThisKey="id", OtherKey="conversationid")]
		public EntitySet<tbConversation_User> tbConversation_Users
		{
			get
			{
				return this._tbConversation_Users;
			}
			set
			{
				this._tbConversation_Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbConversation_tbMessage", Storage="_tbMessages", ThisKey="id", OtherKey="conversationid")]
		public EntitySet<tbMessage> tbMessages
		{
			get
			{
				return this._tbMessages;
			}
			set
			{
				this._tbMessages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbConversation_Users(tbConversation_User entity)
		{
			this.SendPropertyChanging();
			entity.tbConversation = this;
		}
		
		private void detach_tbConversation_Users(tbConversation_User entity)
		{
			this.SendPropertyChanging();
			entity.tbConversation = null;
		}
		
		private void attach_tbMessages(tbMessage entity)
		{
			this.SendPropertyChanging();
			entity.tbConversation = this;
		}
		
		private void detach_tbMessages(tbMessage entity)
		{
			this.SendPropertyChanging();
			entity.tbConversation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbConversation_User")]
	public partial class tbConversation_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _conversationid;
		
		private string _userid;
		
		private System.Nullable<bool> _readstatus;
		
		private System.Nullable<bool> _active;
		
		private EntityRef<tbUser> _tbUser;
		
		private EntityRef<tbConversation> _tbConversation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnconversationidChanging(string value);
    partial void OnconversationidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnreadstatusChanging(System.Nullable<bool> value);
    partial void OnreadstatusChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
		
		public tbConversation_User()
		{
			this._tbUser = default(EntityRef<tbUser>);
			this._tbConversation = default(EntityRef<tbConversation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversationid", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string conversationid
		{
			get
			{
				return this._conversationid;
			}
			set
			{
				if ((this._conversationid != value))
				{
					if (this._tbConversation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnconversationidChanging(value);
					this.SendPropertyChanging();
					this._conversationid = value;
					this.SendPropertyChanged("conversationid");
					this.OnconversationidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._tbUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readstatus", DbType="Bit")]
		public System.Nullable<bool> readstatus
		{
			get
			{
				return this._readstatus;
			}
			set
			{
				if ((this._readstatus != value))
				{
					this.OnreadstatusChanging(value);
					this.SendPropertyChanging();
					this._readstatus = value;
					this.SendPropertyChanged("readstatus");
					this.OnreadstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbConversation_User", Storage="_tbUser", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public tbUser tbUser
		{
			get
			{
				return this._tbUser.Entity;
			}
			set
			{
				tbUser previousValue = this._tbUser.Entity;
				if (((previousValue != value) 
							|| (this._tbUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbUser.Entity = null;
						previousValue.tbConversation_Users.Remove(this);
					}
					this._tbUser.Entity = value;
					if ((value != null))
					{
						value.tbConversation_Users.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(string);
					}
					this.SendPropertyChanged("tbUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbConversation_tbConversation_User", Storage="_tbConversation", ThisKey="conversationid", OtherKey="id", IsForeignKey=true)]
		public tbConversation tbConversation
		{
			get
			{
				return this._tbConversation.Entity;
			}
			set
			{
				tbConversation previousValue = this._tbConversation.Entity;
				if (((previousValue != value) 
							|| (this._tbConversation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbConversation.Entity = null;
						previousValue.tbConversation_Users.Remove(this);
					}
					this._tbConversation.Entity = value;
					if ((value != null))
					{
						value.tbConversation_Users.Add(this);
						this._conversationid = value.id;
					}
					else
					{
						this._conversationid = default(string);
					}
					this.SendPropertyChanged("tbConversation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFriend")]
	public partial class tbFriend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _status;
		
		private EntitySet<tbUser_Friend> _tbUser_Friends;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tbFriend()
		{
			this._tbUser_Friends = new EntitySet<tbUser_Friend>(new Action<tbUser_Friend>(this.attach_tbUser_Friends), new Action<tbUser_Friend>(this.detach_tbUser_Friends));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbFriend_tbUser_Friend", Storage="_tbUser_Friends", ThisKey="id", OtherKey="friend_id")]
		public EntitySet<tbUser_Friend> tbUser_Friends
		{
			get
			{
				return this._tbUser_Friends;
			}
			set
			{
				this._tbUser_Friends.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbUser_Friends(tbUser_Friend entity)
		{
			this.SendPropertyChanging();
			entity.tbFriend = this;
		}
		
		private void detach_tbUser_Friends(tbUser_Friend entity)
		{
			this.SendPropertyChanging();
			entity.tbFriend = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbMessage")]
	public partial class tbMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.Nullable<System.DateTime> _creationtime;
		
		private string _contents;
		
		private string _conversationid;
		
		private string _userid;
		
		private EntitySet<tbAttachmment> _tbAttachmments;
		
		private EntityRef<tbUser> _tbUser;
		
		private EntityRef<tbConversation> _tbConversation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OncreationtimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreationtimeChanged();
    partial void OncontentsChanging(string value);
    partial void OncontentsChanged();
    partial void OnconversationidChanging(string value);
    partial void OnconversationidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    #endregion
		
		public tbMessage()
		{
			this._tbAttachmments = new EntitySet<tbAttachmment>(new Action<tbAttachmment>(this.attach_tbAttachmments), new Action<tbAttachmment>(this.detach_tbAttachmments));
			this._tbUser = default(EntityRef<tbUser>);
			this._tbConversation = default(EntityRef<tbConversation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creationtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> creationtime
		{
			get
			{
				return this._creationtime;
			}
			set
			{
				if ((this._creationtime != value))
				{
					this.OncreationtimeChanging(value);
					this.SendPropertyChanging();
					this._creationtime = value;
					this.SendPropertyChanged("creationtime");
					this.OncreationtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contents", DbType="NVarChar(MAX)")]
		public string contents
		{
			get
			{
				return this._contents;
			}
			set
			{
				if ((this._contents != value))
				{
					this.OncontentsChanging(value);
					this.SendPropertyChanging();
					this._contents = value;
					this.SendPropertyChanged("contents");
					this.OncontentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversationid", DbType="NChar(10)")]
		public string conversationid
		{
			get
			{
				return this._conversationid;
			}
			set
			{
				if ((this._conversationid != value))
				{
					if (this._tbConversation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnconversationidChanging(value);
					this.SendPropertyChanging();
					this._conversationid = value;
					this.SendPropertyChanged("conversationid");
					this.OnconversationidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NChar(10)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._tbUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbMessage_tbAttachmment", Storage="_tbAttachmments", ThisKey="id", OtherKey="messageid")]
		public EntitySet<tbAttachmment> tbAttachmments
		{
			get
			{
				return this._tbAttachmments;
			}
			set
			{
				this._tbAttachmments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbMessage", Storage="_tbUser", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public tbUser tbUser
		{
			get
			{
				return this._tbUser.Entity;
			}
			set
			{
				tbUser previousValue = this._tbUser.Entity;
				if (((previousValue != value) 
							|| (this._tbUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbUser.Entity = null;
						previousValue.tbMessages.Remove(this);
					}
					this._tbUser.Entity = value;
					if ((value != null))
					{
						value.tbMessages.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(string);
					}
					this.SendPropertyChanged("tbUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbConversation_tbMessage", Storage="_tbConversation", ThisKey="conversationid", OtherKey="id", IsForeignKey=true)]
		public tbConversation tbConversation
		{
			get
			{
				return this._tbConversation.Entity;
			}
			set
			{
				tbConversation previousValue = this._tbConversation.Entity;
				if (((previousValue != value) 
							|| (this._tbConversation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbConversation.Entity = null;
						previousValue.tbMessages.Remove(this);
					}
					this._tbConversation.Entity = value;
					if ((value != null))
					{
						value.tbMessages.Add(this);
						this._conversationid = value.id;
					}
					else
					{
						this._conversationid = default(string);
					}
					this.SendPropertyChanged("tbConversation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbAttachmments(tbAttachmment entity)
		{
			this.SendPropertyChanging();
			entity.tbMessage = this;
		}
		
		private void detach_tbAttachmments(tbAttachmment entity)
		{
			this.SendPropertyChanging();
			entity.tbMessage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbUser_Friend")]
	public partial class tbUser_Friend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_id;
		
		private string _friend_id;
		
		private EntityRef<tbFriend> _tbFriend;
		
		private EntityRef<tbUser> _tbUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onfriend_idChanging(string value);
    partial void Onfriend_idChanged();
    #endregion
		
		public tbUser_Friend()
		{
			this._tbFriend = default(EntityRef<tbFriend>);
			this._tbUser = default(EntityRef<tbUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tbUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friend_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string friend_id
		{
			get
			{
				return this._friend_id;
			}
			set
			{
				if ((this._friend_id != value))
				{
					if (this._tbFriend.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfriend_idChanging(value);
					this.SendPropertyChanging();
					this._friend_id = value;
					this.SendPropertyChanged("friend_id");
					this.Onfriend_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbFriend_tbUser_Friend", Storage="_tbFriend", ThisKey="friend_id", OtherKey="id", IsForeignKey=true)]
		public tbFriend tbFriend
		{
			get
			{
				return this._tbFriend.Entity;
			}
			set
			{
				tbFriend previousValue = this._tbFriend.Entity;
				if (((previousValue != value) 
							|| (this._tbFriend.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbFriend.Entity = null;
						previousValue.tbUser_Friends.Remove(this);
					}
					this._tbFriend.Entity = value;
					if ((value != null))
					{
						value.tbUser_Friends.Add(this);
						this._friend_id = value.id;
					}
					else
					{
						this._friend_id = default(string);
					}
					this.SendPropertyChanged("tbFriend");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbUser_tbUser_Friend", Storage="_tbUser", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
		public tbUser tbUser
		{
			get
			{
				return this._tbUser.Entity;
			}
			set
			{
				tbUser previousValue = this._tbUser.Entity;
				if (((previousValue != value) 
							|| (this._tbUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbUser.Entity = null;
						previousValue.tbUser_Friends.Remove(this);
					}
					this._tbUser.Entity = value;
					if ((value != null))
					{
						value.tbUser_Friends.Add(this);
						this._user_id = value.id;
					}
					else
					{
						this._user_id = default(string);
					}
					this.SendPropertyChanged("tbUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class funcBlockFriendListResult
	{
		
		private string _id;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _sex;
		
		private string _nameshow;
		
		private System.Nullable<bool> _active;
		
		private string _role;
		
		private string _connectionid;
		
		private System.Nullable<bool> _onlinestatus;
		
		private string _pathimage;
		
		public funcBlockFriendListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this._birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NChar(10)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this._role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectionid", DbType="NChar(50)")]
		public string connectionid
		{
			get
			{
				return this._connectionid;
			}
			set
			{
				if ((this._connectionid != value))
				{
					this._connectionid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onlinestatus", DbType="Bit")]
		public System.Nullable<bool> onlinestatus
		{
			get
			{
				return this._onlinestatus;
			}
			set
			{
				if ((this._onlinestatus != value))
				{
					this._onlinestatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
	}
	
	public partial class funcSeachFriendListResult
	{
		
		private string _id;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _sex;
		
		private string _nameshow;
		
		private System.Nullable<bool> _active;
		
		private string _role;
		
		private string _connectionid;
		
		private System.Nullable<bool> _onlinestatus;
		
		private string _pathimage;
		
		public funcSeachFriendListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this._birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NChar(10)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this._role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectionid", DbType="NChar(50)")]
		public string connectionid
		{
			get
			{
				return this._connectionid;
			}
			set
			{
				if ((this._connectionid != value))
				{
					this._connectionid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onlinestatus", DbType="Bit")]
		public System.Nullable<bool> onlinestatus
		{
			get
			{
				return this._onlinestatus;
			}
			set
			{
				if ((this._onlinestatus != value))
				{
					this._onlinestatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
	}
	
	public partial class funcConversationSMSResult
	{
		
		private string _conversationid;
		
		private System.Nullable<System.DateTime> _lasttimemodified;
		
		private System.Nullable<bool> _isGroup;
		
		private string _name;
		
		private System.Nullable<bool> _readstatus;
		
		public funcConversationSMSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversationid", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string conversationid
		{
			get
			{
				return this._conversationid;
			}
			set
			{
				if ((this._conversationid != value))
				{
					this._conversationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lasttimemodified", DbType="DateTime")]
		public System.Nullable<System.DateTime> lasttimemodified
		{
			get
			{
				return this._lasttimemodified;
			}
			set
			{
				if ((this._lasttimemodified != value))
				{
					this._lasttimemodified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isGroup", DbType="Bit")]
		public System.Nullable<bool> isGroup
		{
			get
			{
				return this._isGroup;
			}
			set
			{
				if ((this._isGroup != value))
				{
					this._isGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readstatus", DbType="Bit")]
		public System.Nullable<bool> readstatus
		{
			get
			{
				return this._readstatus;
			}
			set
			{
				if ((this._readstatus != value))
				{
					this._readstatus = value;
				}
			}
		}
	}
	
	public partial class funcGetListFriendResult
	{
		
		private string _id;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _sex;
		
		private string _nameshow;
		
		private string _connectionid;
		
		private System.Nullable<bool> _onlinestatus;
		
		private string _pathimage;
		
		private string _friend_id;
		
		public funcGetListFriendResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this._birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectionid", DbType="NChar(50)")]
		public string connectionid
		{
			get
			{
				return this._connectionid;
			}
			set
			{
				if ((this._connectionid != value))
				{
					this._connectionid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onlinestatus", DbType="Bit")]
		public System.Nullable<bool> onlinestatus
		{
			get
			{
				return this._onlinestatus;
			}
			set
			{
				if ((this._onlinestatus != value))
				{
					this._onlinestatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friend_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string friend_id
		{
			get
			{
				return this._friend_id;
			}
			set
			{
				if ((this._friend_id != value))
				{
					this._friend_id = value;
				}
			}
		}
	}
	
	public partial class funcLastSMSConversationResult
	{
		
		private string _contents;
		
		private System.Nullable<System.DateTime> _creationtime;
		
		private string _id;
		
		public funcLastSMSConversationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contents", DbType="NVarChar(MAX)")]
		public string contents
		{
			get
			{
				return this._contents;
			}
			set
			{
				if ((this._contents != value))
				{
					this._contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creationtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> creationtime
		{
			get
			{
				return this._creationtime;
			}
			set
			{
				if ((this._creationtime != value))
				{
					this._creationtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
	
	public partial class funcFindConversationNameResult
	{
		
		private string _userid;
		
		private string _nameshow;
		
		private string _pathimage;
		
		public funcFindConversationNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
	}
	
	public partial class funcOfflineListResult
	{
		
		private string _friend_id;
		
		private string _user_id;
		
		private string _status;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _sex;
		
		private string _nameshow;
		
		private string _connectionid;
		
		private System.Nullable<bool> _onlinestatus;
		
		private string _pathimage;
		
		private string _conversationid;
		
		private System.Nullable<bool> _readstatus;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _lasttimemodified;
		
		public funcOfflineListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friend_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string friend_id
		{
			get
			{
				return this._friend_id;
			}
			set
			{
				if ((this._friend_id != value))
				{
					this._friend_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this._birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectionid", DbType="NChar(50)")]
		public string connectionid
		{
			get
			{
				return this._connectionid;
			}
			set
			{
				if ((this._connectionid != value))
				{
					this._connectionid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onlinestatus", DbType="Bit")]
		public System.Nullable<bool> onlinestatus
		{
			get
			{
				return this._onlinestatus;
			}
			set
			{
				if ((this._onlinestatus != value))
				{
					this._onlinestatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversationid", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string conversationid
		{
			get
			{
				return this._conversationid;
			}
			set
			{
				if ((this._conversationid != value))
				{
					this._conversationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readstatus", DbType="Bit")]
		public System.Nullable<bool> readstatus
		{
			get
			{
				return this._readstatus;
			}
			set
			{
				if ((this._readstatus != value))
				{
					this._readstatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lasttimemodified", DbType="DateTime")]
		public System.Nullable<System.DateTime> lasttimemodified
		{
			get
			{
				return this._lasttimemodified;
			}
			set
			{
				if ((this._lasttimemodified != value))
				{
					this._lasttimemodified = value;
				}
			}
		}
	}
	
	public partial class funcOnlineListResult
	{
		
		private string _friend_id;
		
		private string _user_id;
		
		private string _status;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birth;
		
		private string _sex;
		
		private string _nameshow;
		
		private string _connectionid;
		
		private System.Nullable<bool> _onlinestatus;
		
		private string _pathimage;
		
		private string _conversationid;
		
		private System.Nullable<bool> _readstatus;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _lasttimemodified;
		
		public funcOnlineListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friend_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string friend_id
		{
			get
			{
				return this._friend_id;
			}
			set
			{
				if ((this._friend_id != value))
				{
					this._friend_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth", DbType="Date")]
		public System.Nullable<System.DateTime> birth
		{
			get
			{
				return this._birth;
			}
			set
			{
				if ((this._birth != value))
				{
					this._birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_connectionid", DbType="NChar(50)")]
		public string connectionid
		{
			get
			{
				return this._connectionid;
			}
			set
			{
				if ((this._connectionid != value))
				{
					this._connectionid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onlinestatus", DbType="Bit")]
		public System.Nullable<bool> onlinestatus
		{
			get
			{
				return this._onlinestatus;
			}
			set
			{
				if ((this._onlinestatus != value))
				{
					this._onlinestatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversationid", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string conversationid
		{
			get
			{
				return this._conversationid;
			}
			set
			{
				if ((this._conversationid != value))
				{
					this._conversationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readstatus", DbType="Bit")]
		public System.Nullable<bool> readstatus
		{
			get
			{
				return this._readstatus;
			}
			set
			{
				if ((this._readstatus != value))
				{
					this._readstatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lasttimemodified", DbType="DateTime")]
		public System.Nullable<System.DateTime> lasttimemodified
		{
			get
			{
				return this._lasttimemodified;
			}
			set
			{
				if ((this._lasttimemodified != value))
				{
					this._lasttimemodified = value;
				}
			}
		}
	}
	
	public partial class funcGetListMessageResult
	{
		
		private string _msid;
		
		private string _userid;
		
		private string _nameshow;
		
		private string _contents;
		
		private System.Nullable<System.DateTime> _creationtime;
		
		private string _pathimage;
		
		public funcGetListMessageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msid", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string msid
		{
			get
			{
				return this._msid;
			}
			set
			{
				if ((this._msid != value))
				{
					this._msid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NChar(10)")]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameshow", DbType="NChar(30)")]
		public string nameshow
		{
			get
			{
				return this._nameshow;
			}
			set
			{
				if ((this._nameshow != value))
				{
					this._nameshow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contents", DbType="NVarChar(MAX)")]
		public string contents
		{
			get
			{
				return this._contents;
			}
			set
			{
				if ((this._contents != value))
				{
					this._contents = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creationtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> creationtime
		{
			get
			{
				return this._creationtime;
			}
			set
			{
				if ((this._creationtime != value))
				{
					this._creationtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pathimage", DbType="NChar(50)")]
		public string pathimage
		{
			get
			{
				return this._pathimage;
			}
			set
			{
				if ((this._pathimage != value))
				{
					this._pathimage = value;
				}
			}
		}
	}
	
	public partial class funcGetAllConversationResult
	{
		
		private string _conversationid;
		
		private System.Nullable<bool> _readstatus;
		
		public funcGetAllConversationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conversationid", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string conversationid
		{
			get
			{
				return this._conversationid;
			}
			set
			{
				if ((this._conversationid != value))
				{
					this._conversationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readstatus", DbType="Bit")]
		public System.Nullable<bool> readstatus
		{
			get
			{
				return this._readstatus;
			}
			set
			{
				if ((this._readstatus != value))
				{
					this._readstatus = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
